# Generated by Django 4.0.7 on 2022-08-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='invntory',
            new_name='inventory',
        ),
    ]
