# Generated by Django 4.0.7 on 2022-08-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotions',
            old_name='desctiption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1),
        ),
    ]
